-- MoodTune AI Oracle-compatible schema
-- Note: Oracle uses schemas/users instead of CREATE DATABASE. Create a user/schema
-- and run this script as that user (or connect as SYS and run as needed).

-- USERS table
CREATE TABLE users (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  name VARCHAR2(100) NOT NULL,
  email VARCHAR2(150) NOT NULL,
  password VARCHAR2(255) NOT NULL,
  profile_image VARCHAR2(500) DEFAULT '',
  is_admin NUMBER(1) DEFAULT 0,
  is_verified NUMBER(1) DEFAULT 0,
  verification_token VARCHAR2(255),
  reset_token VARCHAR2(255),
  preferred_language VARCHAR2(10) DEFAULT 'en',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE users ADD CONSTRAINT users_email_uq UNIQUE (email);

-- SONGS table
CREATE TABLE songs (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  title VARCHAR2(200) NOT NULL,
  artist VARCHAR2(200) NOT NULL,
  album VARCHAR2(200) DEFAULT '',
  genre VARCHAR2(100) NOT NULL,
  mood VARCHAR2(100) NOT NULL,
  duration NUMBER DEFAULT 0,
  cover_url VARCHAR2(500) DEFAULT '',
  preview_url VARCHAR2(500) DEFAULT '',
  spotify_id VARCHAR2(100),
  play_count NUMBER DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE songs ADD CONSTRAINT songs_spotify_id_uq UNIQUE (spotify_id);

-- HISTORY table
CREATE TABLE history (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  user_id NUMBER NOT NULL,
  song_id NUMBER NOT NULL,
  emotion_detected VARCHAR2(50) DEFAULT 'neutral',
  "timestamp" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT history_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT history_song_fk FOREIGN KEY (song_id) REFERENCES songs(id) ON DELETE CASCADE
);

-- PLAYLISTS table
CREATE TABLE playlists (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  user_id NUMBER NOT NULL,
  playlist_name VARCHAR2(200) NOT NULL,
  cover_image VARCHAR2(500) DEFAULT '',
  is_public NUMBER(1) DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT playlists_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- PLAYLIST_SONGS join table (composite PK)
CREATE TABLE playlist_songs (
  playlist_id NUMBER NOT NULL,
  song_id NUMBER NOT NULL,
  CONSTRAINT playlist_songs_pk PRIMARY KEY (playlist_id, song_id),
  CONSTRAINT playlist_songs_playlist_fk FOREIGN KEY (playlist_id) REFERENCES playlists(id) ON DELETE CASCADE,
  CONSTRAINT playlist_songs_song_fk FOREIGN KEY (song_id) REFERENCES songs(id) ON DELETE CASCADE
);

-- FAVORITES table
CREATE TABLE favorites (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  user_id NUMBER NOT NULL,
  song_id NUMBER NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT favorites_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT favorites_song_fk FOREIGN KEY (song_id) REFERENCES songs(id) ON DELETE CASCADE,
  CONSTRAINT unique_fav UNIQUE (user_id, song_id)
);

-- Trigger to keep users.updated_at in sync on UPDATE
CREATE OR REPLACE TRIGGER trg_users_updated_at
BEFORE UPDATE ON users
FOR EACH ROW
BEGIN
  :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- End of Oracle schema
